### ISSUE TITLE
I would just like to ask: Once this is setup on my computer. Could I use google assistant on my phone to control SONOS aswell?

### ISSUE THREAD

**Issue by Nedks** [ZachNagengast/SoCoGa#1]
Just wondering.

**Comment by ZachNagengast** [comment]
Yes, google assistant uses the same endpoints as google home.

**Comment by Nedks** [comment]
oh, so would I need a google home to get this to work? Also thanks for the quick reply.

**Comment by ZachNagengast** [comment]
As you mentioned, google assistant on your phone should work fine.
